export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as SearchResult } from './SearchResult';
export { default as ProductDetail } from './ProductDetail';
export { default as Cart } from './Cart';
export { default as Payment } from './Payment';
export { default as OrderCompleted } from './OrderCompleted';
export { default as AboutUs } from './AboutUs';
